### PR TITLE
Process availability tables instead of dropping them

### PR DESCRIPTION
**Pull request by olejandro**

### CODE REVIEW

**Comment by olejandro** [comment]
@siddharth-krishna this should look much better after #182

**Comment by olejandro** [comment]
@siddharth-krishna looks like this one can move forward without the case-insensitive comparison!

**Review by siddharth-krishna — APPROVED** [review]
Looks good, but should we print a warning that there are rows with invalid process/region combinations?

**Comment by olejandro** [comment]
Thanks @siddharth-krishna! No, not in this case, as at this point (m)any invalid combinations would have been introduced by the tool when filling in the defaults. We should be able to avoid it by using the info from the availability tables earlier. I've left a TODO not to forget about it. 😊

**Pull request merged**
