### PR TITLE
Update GAMS version used in CI

### LINKED ISSUE #242: GAMS version used in CI is too old for the demo license

### PR DESCRIPTION
**Pull request by olejandro**
Fixes #242

### CODE REVIEW

**Comment by olejandro** [comment]
@siddharth-krishna looks like this solves the original issue, but points to another one...

**Review by siddharth-krishna — APPROVED** [review]

**Comment by siddharth-krishna** [comment]
I pushed a commit disabling the license stored in the GH secret, and using the inbuilt demo license. It solves the "expired license" issue, but the other issue remains:

> *** Error 282 in /scratch/htc/skrishna/xl2times/benchmarks/out/DemoS_001-all/scenario.run                                     
>    Unable to open include file
>       Hint: Does the filename need to be quoted?

It looks like there has been some change in Gams between version 44.1 and the latest 48.2 in the way it handles file paths (possibly because our paths contain `-` or `_`?). I cannot test v44.1 now because its demo license has expired, I did try v47.6 (the last one with a valid demo license) and it also has the above error. I tried using different values for the `FileCase` argument, but none of them worked for me on linux.

Olex, could you try running Gams on your machine since you have windows and it has case-insensitive paths? Otherwise we might need to get some help from Gams folks, because I don't know how to debug/fix this issue.

**Comment by olejandro** [comment]
Sure, I can take a look! I had to deal with something similar on Linux not too long ago, so maybe it is the same solution.

**Comment by olejandro** [comment]
@siddharth-krishna it looks like GAMS failing is caused by changes in #239.
Undoing the changes to CI, makes it run: https://github.com/etsap-TIMES/xl2times/actions/runs/11882658156/job/33108421476
Let's merge this and fix the CI in #247

**Pull request merged**
