### PR TITLE
Improve I/E handling

### LINKED ISSUE #258: I/E specification in SysSettings
Additional records (representing i/e options) are generated for TIMES-NZ in #256 for the attributes that have i/e options specified in VT files. The discrepancy appears to be due to Veda behaviour described [here](https://veda-documentation.readthedocs.io/en/latest/pages/Migration.html#things-that-are-different) (i.e. <q>redefinition (via any tag in SysSettings) of interpolation options defined in Base/SubRES is ignored in Veda2.0</q>).

Should the tool do the same or should we introduce a switch to control this behaviour?

### PR DESCRIPTION
**Pull request by olejandro**
Closes #258

### CODE REVIEW

**Review by siddharth-krishna — APPROVED** [review]
Looks good. I'm curious, is it not possible for us to modify the processing order of the files to get the same outcome? E.g. `SysSettings` before the other files, so that I/E rules in `SysSettings` are treated as defaults?

**Comment by olejandro** [comment]
>  I'm curious, is it not possible for us to modify the processing order of the files to get the same outcome? E.g. SysSettings before the other files, so that I/E rules in SysSettings are treated as defaults?

The current processing order for tfm tables was introduced in #251:
```
processing_order = ["base", "subres", "trade", "demand", "scen", "syssettings"]
```
According to the [docs](https://veda-documentation.readthedocs.io/en/latest/pages/TagsProcOrder/Tags%20proc%20order.html), this is generally consistent with Veda.

However, since the info from `syssettings.dd` is normally included after `base.dd` and subres files, before this PR the i/e entries generated in syssettings were overwritting those from base and subres. So in order to be able to apply the `defaults` concept, as described by @Antti-L in #258, this PR checks for duplicate i/e definitions in across base, subres and syssettings and removes those from syssettings.

**Comment by Antti-L** [comment]
> `processing_order = ["base", "subres", "trade", "demand", "scen", "syssettings"]`

Yes this is consistent with VEDA, and I guess necessary for the SysSettings processing to see the parameters in all other scenarios. But now, because I am not sure how the user-defined _scenario order_ is handled `xl2times`, I am curious concerning the outcome with respect to the _other scenarios_:  Will the IE options generated by `SysSettings` be overridden also in `xl2times` by any options defined in **regular scenarios** for the same time-series, as they normally should be (based on the scenario order)?

**Comment by olejandro** [comment]
Yes, that's what I would expect. E.g. this is how this list looks for the TIMES-NZ TUI case:
```
  - name: TIMES-NZ-TUI
    input_folder: TIMES-NZ
    inputs:
      - "VT_NI_ELC_V4.xlsx"
      - "VT_NI_IND_V2.xlsx"
      - "VT_NI_OTH_V4.xlsx"
      - "VT_NI_PRI_V4.xlsx"
      - "VT_NI_TRA_V4.xlsx"
      - "VT_SI_ELC_V4.xlsx"
      - "VT_SI_IND_V2.xlsx"
      - "VT_SI_OTH_V4.xlsx"
      - "VT_SI_PRI_V4.xlsx"
      - "VT_SI_TRA_V4.xlsx"
      - "BY_Trans.xlsx"
      - "SuppXLS/Trades/ScenTrade__Trade_Links.xlsx"
      - "SubRES_TMPL/SubRES_NewTech_ELC_TUI.xlsx"
      - "SubRES_TMPL/SubRES_NewTechs_Industry.xlsx"
      - "SubRES_TMPL/SubRES_NewTechs_Industry_Trans.xlsx"
      - "SubRES_TMPL/SubRES_NewTransport-TUI.xlsx"
      - "SubRES_TMPL/SubRES_NewTech_AGR_TUI.xlsx"
      - "SubRES_TMPL/SubRES_NewTech_AGR_TUI_Trans.xlsx"
      - "SubRES_TMPL/SubRES_NewTech_RC.xlsx"
      - "SuppXLS/Trades/ScenTrade_TRADE_PARMS.xlsx"
      - "SysSettings.xlsx"
      - "SuppXLS/Scen_Base_constraints.xlsx"
      - "SuppXLS/Scen_RE_Potentials.xlsx"
      - "SuppXLS/Scen_LoadCurve_COM-FR.xlsx"
      - "SuppXLS/Scen_AF_Renewable.xlsx"
      - "SuppXLS/Scen_WEM_WCM.xlsx"
      - "SuppXLS/Scen_Individualistic.xlsx"
```
This list both limits the files that are read by the tool and defines the output overwriting order. Because of this, the tool currently won't be able to reproduce a case where an input is generated based on a file that is not included in the case.

**Comment by Antti-L** [comment]
Ahh... thanks.  But I see that is defined in `benchmarks.yml`.  How would the user normally define the scenario order for the output?  Would it require listing the Excel files (in the output order) in the command line, or is using a list file possible?

**Comment by olejandro** [comment]
I don't think we have really fixed that part yet, right @siddharth-krishna?

**Comment by Antti-L** [comment]
@olejandro A small follow-up:  I was still curious about whether it indeed works as you described, and therefore I now decided to give it a test on my Windows 11 computer.  I downloaded the current Master branch version, and extracted it to a local folder.  I first tested running `xl2times` with the original **Demo4** model, with the files listed in the command line (and with the regular scenario `Scen_Peak_RSV.xlsx` at the end). The run seemed to work well, although with some unexpected warnings such as the following:
* `WARNING  : datatypes.Tag has an unknown Tag Tag.comagg not in veda-tags.json`
* `WARNING  : Cannot produce table TM_DEFVAL because Attributes does not contain the required columns - tm_defval` 

Anyway, then I tested with adding a default IE option for `COM_PKRSV` into `SysSettings`, and an explicit overriding option for it into  `Scen_Peak_RSV.xlsx`.  However, the output only contained the wrong value (the default).  The correct option defined in `Scen_Peak_RSV.xlsx` thus did not make it to the DD file (it was shown in the raw tables, though). I then tested by removing the default option from SysSettings, and only then I got the correct option written out.

Hence, my conclusion from this test is that currently the handling of the IE defaults **does not seem to work** in the correct way, unless I am doing something wrong?  In addition, I would really suggest to implement a list file option, such that one can specify the scenario order there (with **scenario names** such as `base`, `peak_rsv`, and not file names), because listing all the files (apparently now required also with their subfolder paths) in the command line can get quite cumbersome for users, unless I am missing something.

**Comment by olejandro** [comment]
Thanks @Antti-L! Let's open an issue.

On the warnings, some of them are/were meant for development purposes. We should definitely clean them up / add new ones!

**Pull request merged**
