### PR TITLE
Add TIMES-NZ to benchmarks and refactor CI

### PR DESCRIPTION
**Pull request by olejandro**
...and use checkout@v4

### CODE REVIEW

**Comment by olejandro** [comment]
@siddharth-krishna what do you think? Please feel free to modify...

**Comment by olejandro** [comment]
Great, thanks! Yes, I think it is better to do that. I completely forgot to check whether there were any files in the old format!

**Comment by siddharth-krishna** [comment]
Shall we merge this in for now, and update the CI once the format of the file has been updated?

**Comment by olejandro** [comment]
Sounds good!

**Pull request merged**
