### PR TITLE
Bump openpyxl version past bug and fix CI cache invalidation

### LINKED ISSUE #14: Resolve issue with latest openpyxl
See https://github.com/samwebster/times-excel-reader/commit/8adc5b0e3f61858f4b271fa4a939264e394d1949

### PR DESCRIPTION
**Pull request by samwebster**
Fixes #14

### CODE REVIEW

**Comment by olejandro** [comment]
@siddharth-krishna surprised that this is passing, because there have not been new releases of `openpyxl`...

**Review by siddharth-krishna — CHANGES_REQUESTED** [review]
Ah, since we made the tool into a pip package, dependencies and version bounds have been moved to pyproject.toml, requirements.txt is now in case we want to pin exact versions for the developer environment. (The former should use the least restrictive bounds possible to be compatible with as many user environments as possible.) if you see the CI log, it installed version 3.0.10 or something.

**Comment by olejandro** [comment]
Forgot about that, thanks! I'll just close this then.

**Comment by siddharth-krishna** [comment]
If we do want to upgrade to a higher version of openpyxl (or any other dependency) we should change the version bound in `pyproject.toml`.

**Comment by olejandro** [comment]
Sounds good! It seems that it is taking the `openpyxl` developers some time to resolve the issue, so no need to keep this PR open. We anyway have an issue that tracks it.

**Comment by olejandro** [comment]
Reopening this, since the issue in `openpyxl` seems to have been fixed...

**Comment by olejandro** [comment]
@siddharth-krishna CI is failing due to a regression in the runtime. Is it because we are using cached files second time?

**Review by siddharth-krishna — APPROVED** [review]
Thanks, Olex.

The CI was failing because for some reason Demo 8 was having cache misses for some of the files. This is very strange -- it should only happen if the contents of some Demo 8 input XLSX files change (but that shouldn't happen since we fix the demos repo commit hash) or if Python's hashing algorithm changed between the time the cache was created (>7 months ago) and now.

Perhaps what happened is that in bumping up `openpyxl` we also bumped up the version of `hashlib`? (Sadly GitHub has deleted the log from the last successful CI run 7 months ago, so we can't check this.)

If that's the case, then we should invalidate our previous cache and create a new one. I noticed a bug in the CI yaml with the manual `CACHE_KEY` variable, so I fixed that and invalidated the old cache. I then had to run CI twice, so that the cache created in the 1st attempt could be used in the 2nd attempt and make the runtime regression tests a correct comparison.

Some things we should improve in the future:
- [ ] We should pin all dependency versions in `requirements.txt` and use that in the CI, so that all CI runs use the exact same versions (unless/until we manually bump up a version)
- [ ] We should also take a hash of the `requirements.txt` file and include it in the cache key, since the cache is dependent on the version of `hashlib` used

**Comment by olejandro** [comment]
Great! Thanks @siddharth-krishna
I'll open an issue then.

**Pull request merged**
