### PR TITLE
Convert all docstrings to numpydoc style and add linter check

### PR DESCRIPTION
**Pull request by siddharth-krishna**
This PR unifies the style of all docstrings to the [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) style. I picked it pretty arbitrarily because I thought it was more readable than the google style in the code editor. I also added some lint rules to ruff to enforce docstring conventions.

I'm hoping this PR will fix the formatting issues we're having in the auto-generated API docs at https://xl2times.readthedocs.io/en/latest/api/xl2times.html

In case it's helpful later, I used the `pyment` tool to convert existing docstrings from the rst/google styles to numpydoc, and the [docformatter](https://docformatter.readthedocs.io/en/latest/usage.html) tool to wrap lines inside docstrings: 
```bash
for f in `git ls-files | grep '.py'`; do echo formatting $f; pyment -wet -o numpydoc $f; docformatter --black -i $f; done
```
I modified the code of `pyment` to not create "useless" parameter blocks when the incoming docstring didn't have them, and to not add types to parameter blocks since we anyway have the types in the function signature:
https://github.com/siddharth-krishna/pyment

(I moved ruff above pyright in the pre-commit thinking it might be useful to have the faster linter run before the slower type checker.)

### CODE REVIEW

**Comment by siddharth-krishna** [comment]
(Don't merge yet, it looks like the RTD build has some errors..)

**Comment by olejandro** [comment]
Looks great! Thanks a lot @siddharth-krishna!

**Review by olejandro — APPROVED** [review]

**Comment by SamRWest** [comment]
> This PR unifies the style of all docstrings to the [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) style. I picked it pretty arbitrarily because I thought it was more readable than the google style in the code editor. I also added some lint rules to ruff to enforce docstring conventions.
> 
> I'm hoping this PR will fix the formatting issues we're having in the auto-generated API docs at https://xl2times.readthedocs.io/en/latest/api/xl2times.html
> 
> In case it's helpful later, I used the `pyment` tool to convert existing docstrings from the rst/google styles to numpydoc, and the [docformatter](https://docformatter.readthedocs.io/en/latest/usage.html) tool to wrap lines inside docstrings:
> 
> ```shell
> for f in `git ls-files | grep '.py'`; do echo formatting $f; pyment -wet -o numpydoc $f; docformatter --black -i $f; done
> ```
> 
> I modified the code of `pyment` to not create "useless" parameter blocks when the incoming docstring didn't have them, and to not add types to parameter blocks since we anyway have the types in the function signature: https://github.com/siddharth-krishna/pyment
> 
> (I moved ruff above pyright in the pre-commit thinking it might be useful to have the faster linter run before the slower type checker.)

This is really cool @siddharth-krishna.  I'll definitely be borrowing this for some other projects :)

Is it worth running the pyment/docformat commands as a pre-commit also, so it keeps new commits consistent with the current formatting also, or will the ruff check take care of that now?

**Comment by siddharth-krishna** [comment]
Thanks, Sam. The pyment/docformat workflow I used was a little brittle, and I should clean up my fork and perhaps open an upstream PR, so I didn't add it to the pre-commit yet. I think ruff checks for some formatting issues, which I've enabled. Feel free to suggest/enable other docstring related rules!

**Comment by SamRWest** [comment]
> I modified the code of pyment to not create "useless" parameter blocks when the incoming docstring didn't have them, and to not add types to parameter blocks since we anyway have the types in the function signature: https://github.com/siddharth-krishna/pyment

Did you push your changes to pyment somewhere?  These are exactly the issues I had with the tool when I tried it, so I'd be keen to test your updates.

**Comment by siddharth-krishna** [comment]
Ah whoops, I had forgotten to push. Try commit 6f6915e on my fork. It still needs some cleanup — perhaps I should expose the new behaviour under a flag? Suggestions welcome.

**Pull request merged**
